import { NextRequest } from "next/server";

export const runtime = "nodejs";

// GET /install.sh — the one-command install. The dashboard bakes a pre-blessed
// code into the copy-paste command; this script installs the flow CLI (via the
// canonical signed-channel installer) and then connects THIS machine to THIS
// deployment with that code — no second browser round-trip.
//
//   curl -fsSL <deploy>/install.sh | bash -s -- --connect <deploy> --code <code>
//
// Re-runnable: `flow connect --code` is idempotent (reconnects in place by
// deploymentId). Kept deliberately thin — the heavy lifting (Node/deps/PATH,
// signed coding-CLI install) lives in the canonical setup.sh.
const FLOW_INSTALLER = process.env.FLOW_INSTALLER_URL ?? "https://www.flow.engineer/install.sh";

export async function GET(_req: NextRequest): Promise<Response> {
  const script = `#!/usr/bin/env bash
# Flow — connect this machine to a deployment. Generated by the dashboard.
set -euo pipefail

CONNECT_URL=""
CODE=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --connect) CONNECT_URL="$2"; shift 2 ;;
    --code)    CODE="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if ! command -v flow >/dev/null 2>&1; then
  echo "→ Installing the Flow CLI…"
  curl -fsSL ${FLOW_INSTALLER} | bash
  # setup.sh puts 'flow' on PATH via the user's shell profile; make it usable now.
  export PATH="$HOME/.local/bin:$PATH"
fi

if ! command -v flow >/dev/null 2>&1; then
  echo "✗ Flow CLI installed but not on PATH — open a new terminal and run:"
  echo "    flow connect $CONNECT_URL --code $CODE"
  exit 1
fi

if [ -n "$CONNECT_URL" ] && [ -n "$CODE" ]; then
  echo "→ Connecting this machine to $CONNECT_URL…"
  flow connect "$CONNECT_URL" --code "$CODE"
  echo "✓ Done. Refresh the dashboard tab — running agents on this machine is now enabled."
else
  echo "✓ Flow CLI installed. Connect with: flow connect <dashboard-url>"
fi
`;
  return new Response(script, {
    status: 200,
    headers: { "content-type": "text/x-shellscript; charset=utf-8", "cache-control": "no-store" },
  });
}
