/* oxlint-disable t3code/no-global-process-runtime -- Standalone installer tests require the host platform. */
import * as NodeTest from "node:test";
import * as NodeAssert from "node:assert/strict";
import * as NodeFSP from "node:fs/promises";
import * as NodePath from "node:path";
import * as NodeOS from "node:os";
import * as NodeCrypto from "node:crypto";
import * as NodeChildProcess from "node:child_process";
import * as NodeUtil from "node:util";
const execute = NodeUtil.promisify(NodeChildProcess.execFile);
const root = NodePath.resolve(import.meta.dirname, "..");
NodeTest.test("bootstrap pins the exact legacy cleanup before executing it", async () => {
  const installer = await NodeFSP.readFile(NodePath.join(root, "install.sh"), "utf8");
  const helper = await NodeFSP.readFile(NodePath.join(root, "scripts/retire-legacy-flow.mjs"));
  NodeAssert.equal(
    installer.match(/FLOW_CLEANUP_SHA=(\w+)/)?.[1],
    NodeCrypto.createHash("sha256").update(helper).digest("hex"),
  );
  NodeAssert.ok(
    installer.indexOf("$FLOW_SHASUM -c cleanup.sha256") <
      installer.indexOf('PATH="$FLOW_CLEANUP_PATH"'),
  );
});
NodeTest.test(
  "Mac bootstrap replaces a broken install using only the downloaded runtime",
  {
    skip: !(
      NodeOS.platform() === "darwin" &&
      NodeOS.arch() === "arm64" &&
      process.env.FLOW_TEST_BUNDLE_DIR
    ),
    timeout: 180_000,
  },
  async (t) => {
    const home = await NodeFSP.realpath(
      await NodeFSP.mkdtemp(NodePath.join(NodeOS.tmpdir(), "flow-bootstrap-")),
    );
    t.after(() => NodeFSP.rm(home, { recursive: true, force: true }));
    const write = async (name, text, mode = 0o600) => {
      const file = NodePath.join(home, name);
      await NodeFSP.mkdir(NodePath.dirname(file), { recursive: true });
      await NodeFSP.writeFile(file, text, { mode });
      return file;
    };
    // Only transport is replaced; tar, checksum, bundled Node, adoption and app
    // creation execute for real. Docker is isolated from the developer's daemon.
    await write(
      "tools/curl",
      `#!/bin/bash
while [ "$#" -gt 0 ]; do
  case "$1" in
    https://*) url="$1" ;;
    --output) shift; out="$1" ;;
  esac
  shift
done
case "$url" in
  */retire-legacy-flow.mjs) /bin/cp "$FLOW_TEST_HELPER" "$out" ;;
  */flow-browser-darwin-arm64.tar.gz*) /bin/cp "$FLOW_TEST_BUNDLE_DIR/\u0024{url##*/}" "$out" ;;
  *) exit 42 ;;
esac
`,
      0o700,
    );
    await write("tools/docker", "#!/bin/sh\nexit 127\n", 0o700);
    const original =
      "#!/bin/sh\n# Flow CLI — auto-generated by setup.sh\n# Checkout: " +
      home +
      '/.flow/checkouts/flow\nexec /missing/node /missing/flow.mjs "$@"\n';
    const launcher = await write(".local/bin/flow", original, 0o700);
    await write(".zshrc", 'alias flow="/missing/flow"\nalias keep="echo yes"\n');
    // An earlier install of this same release home left a browser-launcher app.
    await write(
      "Applications/Flow.app/Contents/flow-browser-launcher",
      NodePath.join(home, "release") + "\n",
    );
    await write(".flow/checkouts/flow/data/brain.db", "keep old data");
    await write("Documents/repo/.git", "gitdir: missing");
    await write(
      "Documents/repo/.mcp.json",
      JSON.stringify({
        mcpServers: { "flow-graph": { command: "missing" }, "t3-code": { url: "keep" } },
      }),
    );
    const env = {
      HOME: home,
      PATH: NodePath.join(home, "tools") + ":/usr/bin:/bin:/usr/sbin:/sbin",
      FLOW_TEST_HELPER: NodePath.join(root, "scripts/retire-legacy-flow.mjs"),
      FLOW_TEST_BUNDLE_DIR: process.env.FLOW_TEST_BUNDLE_DIR,
      FLOW_RELEASE_HOME: NodePath.join(home, "release"),
      FLOW_APPLICATIONS_DIR: NodePath.join(home, "Applications"),
    };
    const result = await execute("/bin/bash", [NodePath.join(root, "install.sh")], {
      env,
      timeout: 150_000,
    });
    // The CLI opens a browser; it never installs an app of its own.
    NodeAssert.match(result.stdout, /Start it any time with:/);
    NodeAssert.match(result.stdout, /Create your Brain/);
    NodeAssert.match(await NodeFSP.readFile(launcher, "utf8"), /# flow-managed-launcher/);
    const backups = await NodeFSP.readdir(NodePath.join(home, ".flow/retired"));
    NodeAssert.equal(
      await NodeFSP.readFile(
        NodePath.join(home, ".flow/retired", backups[0], "files", launcher.slice(1)),
        "utf8",
      ),
      original,
    );
    NodeAssert.equal(
      await NodeFSP.readFile(NodePath.join(home, ".flow/checkouts/flow/data/brain.db"), "utf8"),
      "keep old data",
    );
    NodeAssert.deepEqual(
      JSON.parse(await NodeFSP.readFile(NodePath.join(home, "Documents/repo/.mcp.json"), "utf8")),
      { mcpServers: { "t3-code": { url: "keep" } } },
    );
    NodeAssert.equal(
      await NodeFSP.stat(NodePath.join(home, "Applications/Flow.app")).catch(() => null),
      null,
      "the browser-launcher app this home installed earlier should be gone",
    );
    const runtime = await execute(
      NodePath.join(home, "release/current/runtime/bin/node"),
      ["--version"],
      { env },
    );
    NodeAssert.match(runtime.stdout, /^v24\./);
  },
);
const target =
  NodeOS.platform() === "darwin" && NodeOS.arch() === "arm64"
    ? "darwin-arm64"
    : NodeOS.platform() === "linux" && NodeOS.arch() === "x64"
      ? "linux-x64"
      : null;
NodeTest.test(
  "a command copied from a Cloud dashboard installs Flow and connects that Brain",
  { skip: !target, timeout: 60_000 },
  async (t) => {
    const home = await NodeFSP.realpath(
      await NodeFSP.mkdtemp(NodePath.join(NodeOS.tmpdir(), "flow-cloud-install-")),
    );
    t.after(() => NodeFSP.rm(home, { recursive: true, force: true }));
    const write = async (name, text, mode = 0o700) => {
      const file = NodePath.join(home, name);
      await NodeFSP.mkdir(NodePath.dirname(file), { recursive: true });
      await NodeFSP.writeFile(file, text, { mode });
      return file;
    };
    // Stand-ins for the download and the bundle: this exercises the installer's
    // own handling of the dashboard's options, not the release it installs.
    const launcher = await write(
      "launcher",
      `#!/bin/bash
# flow-managed-launcher
printf '%s\\n' "$*" >> "$FLOW_TEST_LOG"
while [ "$#" -gt 0 ]; do [ "$1" = --enrollment-file ] && file=$2; shift; done
{ stat -f %Lp "$file" 2>/dev/null || stat -c %a "$file"; cat "$file"; echo; } >> "$FLOW_TEST_LOG"
[ -z "\${FLOW_TEST_FAIL:-}" ] || { echo 'Setup prompt expired, was already used, or belongs to another Brain.' >&2; exit 1; }
`,
    );
    await write(
      "bundle/runtime/bin/node",
      `#!/bin/bash
case "$*" in *install-bundle*) mkdir -p "$FLOW_RELEASE_HOME/bin" && cp "${launcher}" "$FLOW_RELEASE_HOME/bin/flow" ;; esac
`,
    );
    const asset = `flow-browser-${target}.tar.gz`;
    await execute("tar", [
      "-czf",
      NodePath.join(home, asset),
      "-C",
      NodePath.join(home, "bundle"),
      ".",
    ]);
    const digest = NodeCrypto.createHash("sha256")
      .update(await NodeFSP.readFile(NodePath.join(home, asset)))
      .digest("hex");
    await write(`${asset}.sha256`, `${digest}  ${asset}\n`);
    await write(
      "tools/curl",
      `#!/bin/bash
while [ "$#" -gt 0 ]; do
  case "$1" in https://*) url="$1" ;; --output) shift; out="$1" ;; esac
  shift
done
case "$url" in
  */retire-legacy-flow.mjs) /bin/cp "$FLOW_TEST_HELPER" "$out" ;;
  *) /bin/cp "${home}/$(basename "$url")" "$out" ;;
esac
`,
    );
    const credential = "ab".repeat(32);
    const log = NodePath.join(home, "log");
    const run = (extra = {}) =>
      execute(
        "/bin/bash",
        [
          NodePath.join(root, "install.sh"),
          ...["--cloud", "https://brain.example", "--cloud-brain", "brain-1"],
          ...["--enrollment", credential],
        ],
        {
          env: {
            HOME: home,
            PATH: NodePath.join(home, "tools") + ":/usr/bin:/bin:/usr/sbin:/sbin",
            FLOW_TEST_HELPER: NodePath.join(root, "scripts/retire-legacy-flow.mjs"),
            FLOW_RELEASE_HOME: NodePath.join(home, "release"),
            FLOW_TEST_LOG: log,
            ...extra,
          },
        },
      );
    const connected = await run();
    NodeAssert.match(
      connected.stdout,
      /Connected to your team's Brain at https:\/\/brain\.example/,
    );
    NodeAssert.doesNotMatch(connected.stdout, /Create your Brain/);
    NodeAssert.doesNotMatch(connected.stdout + connected.stderr, new RegExp(credential));
    const [command, mode, saved] = (await NodeFSP.readFile(log, "utf8")).trim().split("\n");
    NodeAssert.match(
      command,
      /^setup --cloud https:\/\/brain\.example --cloud-brain brain-1 --enrollment-file \S+ --harness detected$/,
    );
    NodeAssert.doesNotMatch(command, /--folder/);
    NodeAssert.equal(mode, "600");
    NodeAssert.equal(saved, credential);
    // Nothing of the one-time credential stays on disk.
    const left = await execute("grep", ["-rl", credential, NodePath.join(home, "release")]).catch(
      () => ({ stdout: "" }),
    );
    NodeAssert.equal(left.stdout, "");

    const failed = await run({ FLOW_TEST_FAIL: "1" }).catch((error) => error);
    NodeAssert.equal(failed.code, 1);
    NodeAssert.match(failed.stderr, /Setup prompt expired/);
    NodeAssert.match(failed.stderr, /copy a new one\s+and run it again/);
    NodeAssert.match(failed.stdout, /Flow is installed/);
  },
);
