/* oxlint-disable t3code/no-global-process-runtime -- Standalone installer tests require the host platform. */
import * as NodeTest from "node:test";
import * as NodeAssert from "node:assert/strict";
import * as NodeFSP from "node:fs/promises";
import * as NodePath from "node:path";
import * as NodeOS from "node:os";
import * as NodeCrypto from "node:crypto";
import * as NodeChildProcess from "node:child_process";
import * as NodeUtil from "node:util";
const execute = NodeUtil.promisify(NodeChildProcess.execFile);
const root = NodePath.resolve(import.meta.dirname, "..");
NodeTest.test("bootstrap pins the exact legacy cleanup before executing it", async () => {
  const installer = await NodeFSP.readFile(NodePath.join(root, "install.sh"), "utf8");
  const helper = await NodeFSP.readFile(NodePath.join(root, "scripts/retire-legacy-flow.mjs"));
  NodeAssert.equal(
    installer.match(/FLOW_CLEANUP_SHA=(\w+)/)?.[1],
    NodeCrypto.createHash("sha256").update(helper).digest("hex"),
  );
  NodeAssert.ok(
    installer.indexOf("shasum -a 256 -c cleanup.sha256") <
      installer.indexOf('PATH="$FLOW_CLEANUP_PATH"'),
  );
});
NodeTest.test(
  "Mac bootstrap replaces a broken install using only the downloaded runtime",
  {
    skip: !(
      NodeOS.platform() === "darwin" &&
      NodeOS.arch() === "arm64" &&
      process.env.FLOW_TEST_BUNDLE_DIR
    ),
    timeout: 180_000,
  },
  async (t) => {
    const home = await NodeFSP.realpath(
      await NodeFSP.mkdtemp(NodePath.join(NodeOS.tmpdir(), "flow-bootstrap-")),
    );
    t.after(() => NodeFSP.rm(home, { recursive: true, force: true }));
    const write = async (name, text, mode = 0o600) => {
      const file = NodePath.join(home, name);
      await NodeFSP.mkdir(NodePath.dirname(file), { recursive: true });
      await NodeFSP.writeFile(file, text, { mode });
      return file;
    };
    // Only transport is replaced; tar, checksum, bundled Node, adoption and app
    // creation execute for real. Docker is isolated from the developer's daemon.
    await write(
      "tools/curl",
      `#!/bin/bash
while [ "$#" -gt 0 ]; do
  case "$1" in
    https://*) url="$1" ;;
    --output) shift; out="$1" ;;
  esac
  shift
done
case "$url" in
  */retire-legacy-flow.mjs) /bin/cp "$FLOW_TEST_HELPER" "$out" ;;
  */flow-browser-darwin-arm64.tar.gz*) /bin/cp "$FLOW_TEST_BUNDLE_DIR/\u0024{url##*/}" "$out" ;;
  *) exit 42 ;;
esac
`,
      0o700,
    );
    await write("tools/docker", "#!/bin/sh\nexit 127\n", 0o700);
    const original =
      "#!/bin/sh\n# Flow CLI — auto-generated by setup.sh\n# Checkout: " +
      home +
      '/.flow/checkouts/flow\nexec /missing/node /missing/flow.mjs "$@"\n';
    const launcher = await write(".local/bin/flow", original, 0o700);
    await write(".zshrc", 'alias flow="/missing/flow"\nalias keep="echo yes"\n');
    await write(".flow/checkouts/flow/data/brain.db", "keep old data");
    await write("Documents/repo/.git", "gitdir: missing");
    await write(
      "Documents/repo/.mcp.json",
      JSON.stringify({
        mcpServers: { "flow-graph": { command: "missing" }, "t3-code": { url: "keep" } },
      }),
    );
    const env = {
      HOME: home,
      PATH: NodePath.join(home, "tools") + ":/usr/bin:/bin:/usr/sbin:/sbin",
      FLOW_TEST_HELPER: NodePath.join(root, "scripts/retire-legacy-flow.mjs"),
      FLOW_TEST_BUNDLE_DIR: process.env.FLOW_TEST_BUNDLE_DIR,
      FLOW_RELEASE_HOME: NodePath.join(home, "release"),
      FLOW_APPLICATIONS_DIR: NodePath.join(home, "Applications"),
    };
    const result = await execute("/bin/bash", [NodePath.join(root, "install.sh")], {
      env,
      timeout: 150_000,
    });
    NodeAssert.match(result.stdout, /Installed .*Flow.app/);
    NodeAssert.match(await NodeFSP.readFile(launcher, "utf8"), /# flow-managed-launcher/);
    const backups = await NodeFSP.readdir(NodePath.join(home, ".flow/retired"));
    NodeAssert.equal(
      await NodeFSP.readFile(
        NodePath.join(home, ".flow/retired", backups[0], "files", launcher.slice(1)),
        "utf8",
      ),
      original,
    );
    NodeAssert.equal(
      await NodeFSP.readFile(NodePath.join(home, ".flow/checkouts/flow/data/brain.db"), "utf8"),
      "keep old data",
    );
    NodeAssert.deepEqual(
      JSON.parse(await NodeFSP.readFile(NodePath.join(home, "Documents/repo/.mcp.json"), "utf8")),
      { mcpServers: { "t3-code": { url: "keep" } } },
    );
    await NodeFSP.stat(NodePath.join(home, "Applications/Flow.app/Contents/Info.plist"));
    const runtime = await execute(
      NodePath.join(home, "release/current/runtime/bin/node"),
      ["--version"],
      { env },
    );
    NodeAssert.match(runtime.stdout, /^v24\./);
  },
);
