/* oxlint-disable t3code/no-global-process-runtime -- Standalone installer tests require the host platform. */
import * as NodeTest from "node:test";
const { test } = NodeTest;
import * as NodeAssert from "node:assert/strict";
const assert = NodeAssert;
import * as NodeFSP from "node:fs/promises";
const fs = NodeFSP;
import * as NodePath from "node:path";
const { join, dirname } = NodePath;
import * as NodeOS from "node:os";
const { tmpdir } = NodeOS;
import * as NodeChildProcess from "node:child_process";
const { spawn, execFile } = NodeChildProcess;
import * as NodeUtil from "node:util";
const { promisify } = NodeUtil;
import * as NodeEvents from "node:events";
const { once } = NodeEvents;
import {
  retireLegacyFlow,
  cleanIntegration,
  cleanShell,
  cleanInstructions,
  parseConfig,
} from "./retire-legacy-flow.mjs";
const execute = promisify(execFile);
async function fixture(t) {
  const home = await fs.realpath(await fs.mkdtemp(join(tmpdir(), "flow-retire-")));
  t.after(() => fs.rm(home, { recursive: true, force: true }));
  const write = async (rel, text) => {
    const file = join(home, rel);
    await fs.mkdir(dirname(file), { recursive: true });
    await fs.writeFile(file, text);
    return file;
  };
  return { home, write };
}
const noTools = async () => {
  throw Error("No external tools installed");
};
test("retire broken legacy launcher and alias without invoking old Node; preserve data and exact backup", async (t) => {
  const { home, write } = await fixture(t);
  const original =
    "#!/bin/sh\n# Flow CLI — auto-generated by setup.sh\n# Checkout: " +
    home +
    '/.flow/checkouts/flow\nexec /missing/node /missing/flow.mjs "$@"\n';
  const launcher = await write(".local/bin/flow", original);
  await write(".zshrc", 'export OTHER=1\nalias flow="/missing/flow"\nalias flower="echo hello"\n');
  await write(".flow/checkouts/flow/data/brain.db", "precious old data");
  const result = await retireLegacyFlow({ home, path: "", run: noTools, log: () => {} });
  await assert.rejects(fs.stat(launcher), { code: "ENOENT" });
  assert.equal(
    await fs.readFile(join(result.backup, "files", launcher.slice(1)), "utf8"),
    original,
  );
  assert.match(
    await fs.readFile(join(home, ".zshrc"), "utf8"),
    /# Retired legacy Flow: alias flow=/,
  );
  assert.match(await fs.readFile(join(home, ".zshrc"), "utf8"), /alias flower=/);
  assert.equal(
    await fs.readFile(join(home, ".flow/checkouts/flow/data/brain.db"), "utf8"),
    "precious old data",
  );
});
test("removes Flow integration only, preserves neighboring hook entries and new Brain MCP", () => {
  const value = {
    mcpServers: {
      "flow-graph": { command: "legacy" },
      "t3-code": { url: "current" },
      other: { command: "other" },
    },
    hooks: {
      PostToolUse: [
        {
          matcher: "*",
          hooks: [{ command: "/home/a/.flow/bin/flow-hook tool" }, { command: "my-hook" }],
        },
      ],
    },
  };
  const result = cleanIntegration(value);
  assert.deepEqual(result.mcpServers, {
    "t3-code": { url: "current" },
    other: { command: "other" },
  });
  assert.deepEqual(result.hooks.PostToolUse, [{ matcher: "*", hooks: [{ command: "my-hook" }] }]);
  assert.ok(value.mcpServers["flow-graph"]);
});
test("uses recorded repositories, backs up configs, disables stale hooks, and is idempotent", async (t) => {
  const { home, write } = await fixture(t),
    repo = join(home, "repo");
  await write(".flow/integrations.json", JSON.stringify({ repos: { [repo]: {} } }));
  await write(
    "repo/.mcp.json",
    JSON.stringify({
      mcpServers: { "flow-graph": { command: "legacy" }, mine: { command: "keep" } },
    }),
  );
  await write(
    "repo/AGENTS.md",
    "My instructions\n<!-- flow:begin — managed -->\nOld instructions\n<!-- flow:end -->\n",
  );
  await write(".flow/bin/flow-hook", '#!/missing/node\nthrow Error("old")');
  const run = (options) =>
    retireLegacyFlow({ home, path: "", run: noTools, log: () => {}, ...options });
  await run();
  assert.deepEqual(JSON.parse(await fs.readFile(join(repo, ".mcp.json"), "utf8")), {
    mcpServers: { mine: { command: "keep" } },
  });
  assert.equal(await fs.readFile(join(repo, "AGENTS.md"), "utf8"), "My instructions\n");
  await execute("/bin/sh", [join(home, ".flow/bin/flow-hook")]);
  await execute(process.execPath, [join(home, ".flow/bin/flow-hook")]);
  assert.deepEqual((await run()).changed, []);
});
test("does not replace new Flow or unrelated binaries", async (t) => {
  const { home, write } = await fixture(t);
  const file = await write(".local/bin/flow", "#!/bin/sh\n# flow-managed-launcher\nnew code");
  const result = await retireLegacyFlow({ home, path: "", run: noTools, log: () => {} });
  assert.deepEqual(result.changed, []);
  assert.match(await fs.readFile(file, "utf8"), /new code/);
  assert.equal(
    cleanShell('alias flow="node flow-browser/current/scripts/flow-release.mjs"\n'),
    'alias flow="node flow-browser/current/scripts/flow-release.mjs"\n',
  );
});
test("stops only containers matching both the legacy name and database image", async (t) => {
  const { home } = await fixture(t),
    calls = [];
  const fixtures = {
    a: {
      Name: "/flow-falkordb",
      Config: { Image: "falkordb/falkordb:latest" },
      HostConfig: { RestartPolicy: { Name: "unless-stopped", MaximumRetryCount: 0 } },
      State: { Running: true },
    },
    b: { Name: "/redis", Config: { Image: "redis:7" } },
    c: { Name: "/flow-falkordb-unrelated", Config: { Image: "postgres:16" } },
  };
  const run = async (bin, args) => {
    calls.push([bin, ...args]);
    if (args[0] === "ps") return { stdout: "a b c" };
    if (args[0] === "inspect") return { stdout: JSON.stringify([fixtures[args[1]]]) };
    return { stdout: "" };
  };
  const result = await retireLegacyFlow({ home, path: "", run, log: () => {} });
  assert.deepEqual(result.stopped, ["/flow-falkordb"]);
  const saved = JSON.parse(await fs.readFile(join(result.backup, "containers.jsonl"), "utf8"));
  assert.deepEqual(saved.restartPolicy, fixtures.a.HostConfig.RestartPolicy);
  assert.equal(saved.wasRunning, true);
  assert.deepEqual(
    calls.filter((x) => x[1] === "stop"),
    [["docker", "stop", "a"]],
  );
  assert.ok(!calls.some((x) => x.includes("rm")));
});
test(
  "stale port records never terminate a listener outside the verified legacy checkout",
  { skip: NodeOS.platform() !== "darwin", timeout: 10_000 },
  async (t) => {
    const { home, write } = await fixture(t),
      root = join(home, ".flow/checkouts/flow");
    await write(
      ".flow/checkouts/flow/package.json",
      JSON.stringify({ name: "flow", bin: { flow: "bin/flow.mjs" } }),
    );
    await fs.mkdir(join(root, "orchestrator"), { recursive: true });
    async function listener(cwd) {
      const child = spawn(
        process.execPath,
        [
          "-e",
          "const net=require('node:net');const server=net.createServer();server.listen(0,'127.0.0.1',()=>console.log(server.address().port));",
        ],
        { cwd, stdio: ["ignore", "pipe", "pipe"] },
      );
      t.after(() => {
        if (child.exitCode === null && child.signalCode === null) child.kill();
      });
      const [data] = await once(child.stdout, "data");
      return { child, port: Number(data.toString().trim()) };
    }
    const owned = await listener(join(root, "orchestrator")),
      foreign = await listener(home);
    await write(
      ".flow/checkouts/flow/data/projects/test/project.json",
      JSON.stringify({ ports: { gateway: owned.port, orchestrator: foreign.port } }),
    );
    const exit = once(owned.child, "exit");
    const result = await retireLegacyFlow({
      home,
      path: "",
      run: (bin, args) => (bin === "docker" ? noTools() : execute(bin, args)),
      log: () => {},
    });
    await exit;
    assert.equal(foreign.child.exitCode, null);
    assert.equal(foreign.child.signalCode, null);
    assert.ok(result.warnings.some((x) => x.includes(String(foreign.port))));
    assert.deepEqual(result.stopped, [`legacy service on ${owned.port}`]);
  },
);

test("cleans unregistered repositories and JSONC without damaging URL strings or other MCP servers", async (t) => {
  const { home, write } = await fixture(t);
  await write("Documents/repo/.git", "gitdir: elsewhere");
  await write(
    "Documents/repo/.mcp.json",
    '{// comment\n"mcpServers":{"flow-graph":{"command":"old"},"mine":{"url":"https://example.test/a/*b*/",},},}',
  );
  await write(
    "Documents/repo/.codex/config.toml",
    'model="mine"\n[mcp_servers.flow-graph]\ncommand="old"\n[mcp_servers.flow-graph.env]\nOLD="yes"\n[mcp_servers.t3-code]\nurl="keep"\n',
  );
  await retireLegacyFlow({ home, path: "", run: noTools, log: () => {} });
  const result = parseConfig(await fs.readFile(join(home, "Documents/repo/.mcp.json"), "utf8"));
  assert.deepEqual(result, { mcpServers: { mine: { url: "https://example.test/a/*b*/" } } });
  assert.equal(
    await fs.readFile(join(home, "Documents/repo/.codex/config.toml"), "utf8"),
    'model="mine"\n[mcp_servers.t3-code]\nurl="keep"\n',
  );
  assert.equal(cleanInstructions("unrelated\n"), "unrelated\n");
});
test("retires multiline shell functions while leaving neighboring configuration intact", () => {
  const original =
    'export KEEP=1\nflow() {\n  /missing/node /old/bin/flow.mjs "$@"\n}\nalias other="keep"\n';
  const result = cleanShell(original);
  assert.match(result, /# Retired legacy Flow: flow\(\) \{/);
  assert.match(result, /# Retired legacy Flow: }/);
  assert.match(result, /^alias other="keep"$/m);
});
